### ISSUE TITLE
JOSS-REVIEW: update installation instructions

### ISSUE THREAD

**Issue by JannisHoch** [IMMM-SFA/mosartwmpy#35]
Dear @thurber,
I will review this model for JOSS and look very much forward to it.
I have cloned the source code and am now trying to install it on my local machine.
Doing so, I find that the installation instructions are too short - currently, it is only referred to a virtual env if you have Python  >=3.9. But how to install if if I have a lower version number?
Please add a more elaborated yet concise installation instruction to your README + docs. Once I know how to install the package (and it actually works), I will continue the review process.
Thanks!

**Comment by thurber** [comment]
Thanks @JannisHoch, appreciate the feedback!

`mosartwmpy` officially only supports Python >= 3.9.*, in order to maintain access to the latest language features. `[pyenv](https://github.com/pyenv/pyenv)` can be a great way to maintain different versions of Python for different situations by using virtual environments, or using an IDE such as [PyCharm](https://www.jetbrains.com/pycharm/) can automate the creation/management of these virtual environments.

I'm hesitant to include instructions for `pyenv` directly in the README, since their process could change in the future, but I do want to make sure the `mosartwmpy` documentation is sufficient. Can we try walking through the `pyenv` steps here, and then see what makes sense to add to the docs?


FYI https://github.com/openjournals/joss-reviews/issues/3221

**Comment by thurber** [comment]
To create a Python 3.9 virtual environment, try the following steps:

Install `pyenv`:
* if on Mac, use [brew](https://brew.sh/): `brew install pyenv`
* if on a linux system, try [pyenv-installer](https://github.com/pyenv/pyenv-installer)
* if on Windows, try [pyenv-win](https://github.com/pyenv-win/pyenv-win)

Install Python 3.9:
* in a shell, run `pyenv install 3.9.1`

Activate Python 3.9 in the current shell
* in the shell, run `pyenv shell 3.9.1`

Proceed with the install of `mosartwmpy`:
* in the same shell, run `pip install mosartwmpy`

Now you can interact with mosartwmpy in this current shell session; if you start a new shell session you will need to run `pyenv shell 3.9.1` again before proceeding.

**Comment by JannisHoch** [comment]
Thanks for the link to the JOSS review. This is indeed why I have created the issue - I am currently reviewing this submission ;)

I understand your concerns. I also don't require you to explain all details, but an overall explanation should definitely be in the installation description of your package. The one you provide here should suffice in my opinion, except for one aspect: do I need to re-install `mosartmwpy` every time I initiate a new Python 3.9 shell? Or can I re-load the Python 3.9 shell and all packages installed in this shell are available again?

Without such an outline people interested to use your software will first have to look up how `pyenv` works, which is not what I consider to be the way to go.

**Comment by thurber** [comment]
Yup, just wanted to cross-link the review issue with this one! The Python 3.9 shell environment should maintain all previously pip installed software and dependencies each time it is activated. 

I agree that managing Python environments is overly difficult and can be a barrier to entry. I will add these steps to a section in the [readthedocs](https://mosartwmpy.readthedocs.io/en/latest/) page and link to it from the README. This way if folks have their own method of managing Python versions, they can skip over this section. What do you think?

I will create a pull request for this and link it here!

**Comment by thurber** [comment]
I'll merge this PR #36 then, which will close the issue automatically -- but feel free to reopen if further clarification is needed!
