### ISSUE TITLE
[JOSS review] Python version and Dependecies

### ISSUE THREAD

**Issue by cheginit** [IMMM-SFA/mosartwmpy#43]
I am wondering what's reason behind not supporting Python 3.7+. What specific features of Python 3.9 is being used in the code? Pinning the dependencies can limit the usage of the project with other packages. Although one can create several environments, having such unnecessary pinned dependencies might affects the user experience.

The `requirements.txt` includes unnecessary dependencies:

```bash
recommonmark
setuptools
sphinx
sphinx-rtd-theme
```

Some other suggestions:

* I suggest to use `conda` instead of `pyenv`, since you're relying on scientific Python libraries, they tend to be orders of magnitudes faster when installed via `conda-forge`.
* You don't think you need both `pyarrow` and `fastparquet` since they both do the same thing. `pyarrow` is the default `parquet` engine in `pandas`.
* When using `h5netcdf` instead of `netcdf4` you need to be aware of, and inform the user about, the difference that are documented on [`xarray`'s website](https://xarray.pydata.org/en/stable/user-guide/io.html):
> There may be minor differences in the Dataset object returned when reading a NetCDF file with different engines. For example, single-valued attributes are returned as scalars by the default engine=netcdf4, but as arrays of size (1,) when reading with engine=h5netcdf.

Overall, I think the dependencies need a reevaluation.

EDIT: Reference to openjournals/joss-reviews#3221

**Comment by thurber** [comment]
Fair point, many folks are bringing up the Python version concerns. I briefly tried to make use of some of the new shared memory semantics of 3.9, but abandoned that effort -- honestly my main concern is to push folks to keep up to date on their software tooling, but that isn't really the job of a library. I will update to ensure support for 3.7+

**Comment by cheginit** [comment]
Yes, I understand. The main issue with not supporting the Python versions that haven't reached EOL is compatibility with other libraries. Version 3.6's EOL is in 7 months and most of the major libraries have already dropped support for it. So I think 3.7+ support is reasonable.

**Comment by thurber** [comment]
In #46, I have set the minimum python version to 3.7 and moved the dependencies related to building the documentation into the `extra_require` section such that they are optional. Also, removed `fastparquet` dependency since I'm not using it anywhere.

Wanted to respond to your other points as well:
* conda -- I think this is a good idea; I need to learn how to submit a package to conda-forge, so I will make a separate issue for this
* `h5netcdf` vs `netcdf4` -- for all the model outputs i'm using the default `netcdf4` engine; the one place `h5netcdf` is used is when creating a compressed file from all the static grid/model variables, which is mostly just used for the unit tests (i found this engine created slightly smaller files and read them slightly faster). It is unnecessary complexity though so I will make another issue to back out this requirement.

**Comment by cheginit** [comment]
That's looks great!

Regarding conda, that's a (strong) suggestion and not a requirement for JOSS. For development and testing, I highly recommend [MambaForge](https://github.com/conda-forge/miniforge). For Github Actions, you can take a look at the [action file](https://github.com/cheginit/pynhd/blob/main/.github/workflows/test.yml) that I am using in one of my projects. It uses MambaForge and caching.

Regarding `h5netcdf`, I agree that it's an unnecessary complexity.
